import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import clsx from "clsx";
import { createImageWrapperClasses, createTitleClasses, createSubtitleClasses } from "../styles/utils";
import { ArrowUpCircle, DownloadCloud, LifeBuoy, Rocket, Server, Wand2, } from "lucide-react";
import { useState } from "react";
import { AnchorLink, Heading, HighlightText, Section, SharedCard, SharedImageDisplay, useSettings, } from "@lemon-site/shared-ui";
import ImageGalleryModal from "@/components/ImageGalleryModal";
export default function InstallationGuide() {
    const { isMotionDisabled } = useSettings();
    const imagePathBase = "/images/install-guide/";
    const pageImages = [
        `${imagePathBase}01.png`,
        `${imagePathBase}02.png`,
        `${imagePathBase}03.png`,
        `${imagePathBase}04.png`,
        `${imagePathBase}05.png`,
        `${imagePathBase}06.png`,
        `${imagePathBase}07.png`,
        `${imagePathBase}08.png`,
        `${imagePathBase}09.png`,
    ];
    const [isGalleryOpen, setIsGalleryOpen] = useState(false);
    const [currentImageIndex, setCurrentImageIndex] = useState(0);
    const openGallery = (index) => {
        if (pageImages[index]) {
            setCurrentImageIndex(index);
            setIsGalleryOpen(true);
        }
    };
    const closeGallery = () => setIsGalleryOpen(false);
    const nextImage = () => setCurrentImageIndex((prev) => {
        let next = prev + 1;
        while (next < pageImages.length && !pageImages[next])
            next++;
        return next < pageImages.length ? next : prev;
    });
    const prevImage = () => setCurrentImageIndex((prev) => {
        let p = prev - 1;
        while (p >= 0 && !pageImages[p])
            p--;
        return p >= 0 ? p : prev;
    });
    const textBaseStyles = "font-lostnav text-base sm:text-lg leading-relaxed text-lavender-200 theme-is-light:text-themeLight-text text-justify";
    const accentLinkStyles = clsx("font-semibold transition-colors duration-200 underline hover:no-underline", "text-lemon-400 hover:text-lavender-300", "theme-is-light:text-themeLight-linkText theme-is-light:hover:text-themeLight-linkTextHover");
    const codeStyles = clsx("font-mono text-sm px-1.5 py-0.5 rounded break-all", "text-lemon-300 bg-slate-700/60", "theme-is-light:text-themeLight-codeText theme-is-light:bg-themeLight-codeBg");
    const tocItems = [
        { id: "introduction-section", title: "1. Introduction" },
        { id: "system-requirements-section", title: "2. System Requirements" },
        { id: "download-section", title: "3. Where to Download" },
        { id: "installation-steps-intro-section", title: "4. Installation Steps" },
        { id: "first-run-section", title: "5. First Run & Initial Setup" },
        { id: "updating-app-section", title: "6. Updating the Application" },
        { id: "troubleshooting-section", title: "7. Troubleshooting" },
    ];
    const quickNavItems = [
        { id: "system-requirements-section", title: "Requirements", icon: Server },
        { id: "download-section", title: "Download", icon: DownloadCloud },
        { id: "installation-steps-intro-section", title: "Installation", icon: Wand2 },
        { id: "first-run-section", title: "First Run", icon: Rocket },
        { id: "updating-app-section", title: "Updating", icon: ArrowUpCircle },
        { id: "troubleshooting-section", title: "Troubleshoot", icon: LifeBuoy },
    ];
    const method1CardId = "installation-method-exe";
    const method2CardId = "installation-method-source";
    return (_jsxs(Section, { id: "installation-guide", className: "min-h-screen pt-20 pb-20", children: [_jsxs("div", { className: "max-w-7xl mx-auto px-4", children: [_jsxs(Heading, { size: "xl", className: clsx("mb-12 font-losttitle text-center sm:text-center", "text-white", "theme-is-light:text-themeLight-headingText"), children: [" ", "Installation Guide", " "] }), _jsxs(SharedCard, { id: tocItems[0].id, motion: { enableEntry: !isMotionDisabled }, className: "mb-10 md:mb-12", title: {
                            content: tocItems[0].title.substring(tocItems[0].title.indexOf(" ") + 1),
                            level: "h2",
                            className: createTitleClasses()
                        }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: [_jsxs("p", { className: "mb-4", children: [" ", "Welcome to the installation guide for", " ", _jsx(HighlightText, { children: "osu! Lost Scores Analyzer" }), "! This application is designed for osu! (Stable) players to help you find previously unnoticed or \"lost\" scores that might surpass your current personal bests, and to analyze your performance.", " "] }), _jsxs("p", { className: "mb-4", children: [" ", "On this page, you will find instructions on how to download, install, and perform the first run of the application.", " "] }), _jsx("div", { className: clsx("p-4 my-4 rounded-r-md", "bg-slate-800/60 border-l-4 border-lemon-400", "theme-is-light:bg-themeLight-primaryLightBg theme-is-light:border-l-4 theme-is-light:border-themeLight-primary"), children: _jsxs("p", { className: clsx("text-lavender-100", "theme-is-light:text-themeLight-text"), children: [" ", _jsx("strong", { children: "Important:" }), " The application is intended only for osu!stable and does not support osu!lazer and unofficial servers.", " "] }) }), _jsxs("div", { className: clsx("mt-8 pt-6", "border-t border-slate-700/50", "theme-is-light:border-themeLight-border/50"), children: [_jsxs("h3", { className: clsx("text-2xl font-semibold font-losttitle text-center sm:text-center mb-6", "text-white", "theme-is-light:text-themeLight-headingText"), children: [" ", "Quick Navigation", " "] }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 text-center", children: quickNavItems.map((item) => {
                                            const Icon = item.icon;
                                            return (_jsxs(AnchorLink, { to: `#${item.id}`, className: clsx("block p-4 rounded-lg transition-all duration-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-opacity-75", "bg-slate-800/50 hover:bg-slate-700/70 border border-transparent hover:border-purple-400/70 focus-visible:ring-purple-400", "theme-is-light:bg-themeLight-card/70 theme-is-light:hover:bg-white theme-is-light:hover:border-themeLight-primary theme-is-light:focus-visible:ring-themeLight-primary"), children: [_jsx(Icon, { size: 32, className: "mx-auto mb-3 text-purple-400 theme-is-light:text-themeLight-primary", strokeWidth: 1.5 }), _jsx("span", { className: "font-semibold font-lostnav text-sm text-white theme-is-light:text-themeLight-headingText", children: item.title })] }, item.id));
                                        }) })] })] }), _jsxs("div", { className: "space-y-10 md:space-y-12", children: [_jsx(SharedCard, { id: tocItems[1].id, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: tocItems[1].title.substring(tocItems[1].title.indexOf(" ") + 1),
                                    level: "h2",
                                    className: createTitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: _jsxs("ul", { className: "list-disc list-outside pl-5 mb-4 space-y-3", children: [_jsxs("li", { children: [" ", _jsx("strong", { children: "Operating System:" }), " Windows 10 / Windows 11. Currently, there is no official support for macOS and Linux. Users of these systems can try installing from source code, but stable operation is not guaranteed.", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "osu! Client:" }), " Installed osu! (Stable).", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "Internet Connection:" }), " Required for downloading the application, its dependencies (on the first run of the .exe), and for fetching data from the osu! API.", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "For installation from source code:" }), _jsxs("ul", { className: "list-circle list-outside pl-5 mt-2 space-y-2", children: [_jsxs("li", { children: ["Python (version 3.9 or newer recommended). Download from the official Python website:", " ", _jsx("a", { href: "https://www.python.org/downloads/", target: "_blank", rel: "noopener noreferrer", className: clsx(accentLinkStyles, "break-all"), children: "https://www.python.org/downloads/" })] }), _jsx("li", { children: "Pip (usually installed with Python)." }), _jsx("li", { children: "Git (recommended for convenient updates)." }), _jsx("li", { children: "Key dependencies: PySide6, pandas, requests, Pillow, rosu-pp-py, and others from requirements.txt" })] })] })] }) }), _jsxs(SharedCard, { id: tocItems[2].id, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: tocItems[2].title.substring(tocItems[2].title.indexOf(" ") + 1),
                                    level: "h2",
                                    className: createTitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: [_jsxs("p", { className: "mb-4", children: [" ", "You can download the latest version of", " ", _jsx(HighlightText, { children: "osu! Lost Scores Analyzer" }), " from the project's GitHub Releases page: ", _jsx("br", {}), " ", _jsx("a", { href: "https://github.com/kz-lemon4ik/osu-lost-scores/releases", target: "_blank", rel: "noopener noreferrer", className: `${accentLinkStyles} break-all`, children: "https://github.com/kz-lemon4ik/osu-lost-scores/releases" }), " "] }), _jsxs("p", { className: "mb-4", children: [" ", "It is recommended to always download the most recent release, marked as \"Latest\".", " "] }), _jsx(SharedImageDisplay, { src: pageImages[0], alt: "GitHub Releases page", onClick: () => openGallery(0), placeholderText: "[SCREENSHOT: GitHub Releases page with .exe highlighted.]", className: createImageWrapperClasses(), enableHoverEffect: false })] }), _jsx(SharedCard, { id: tocItems[3].id, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: tocItems[3].title.substring(tocItems[3].title.indexOf(" ") + 1),
                                    level: "h2",
                                    className: createTitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: _jsx("p", { className: "mb-4", children: "There are two ways to install the application:" }) }), _jsxs(SharedCard, { id: method1CardId, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: "1. Using the Executable File (.exe) - Recommended Method",
                                    level: "h3",
                                    className: createSubtitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: [_jsx("p", { className: "mb-4", children: "This method is the simplest and suitable for most Windows users." }), _jsxs("ol", { className: "list-decimal list-outside pl-5 mb-4 space-y-3", children: [_jsxs("li", { children: ["Navigate to the GitHub Releases page (link above) and download the", " ", _jsx("code", { className: codeStyles, children: "osu-Lost-Scores-Analyzer-Launcher.exe" }), " file."] }), _jsx("li", { children: "Save the downloaded .exe file to any convenient location." }), _jsx("li", { children: "Run the downloaded .exe file." }), _jsxs("li", { children: [" ", "On the first launch, a launcher window will open and automatically install dependencies. This may take some time.", " ", _jsx(SharedImageDisplay, { src: pageImages[1], alt: "Launcher installing dependencies", onClick: () => openGallery(1), placeholderText: "[SCREENSHOT: Launcher window during dependency installation.]", className: createImageWrapperClasses(), enableHoverEffect: false }), " "] }), _jsx("li", { children: "After successful installation, the main application will automatically start." }), _jsxs("li", { children: [" ", "On subsequent launches, the launcher quickly checks for updates before starting the main application.", " ", _jsx(SharedImageDisplay, { src: pageImages[2], alt: "Launcher on subsequent launches", onClick: () => openGallery(2), placeholderText: "[SCREENSHOT: Launcher window (subsequent launches).]", className: createImageWrapperClasses(), enableHoverEffect: false }), " "] }), _jsx("li", { children: "Proceed to \"First Run and Initial Setup\"." })] })] }), _jsxs(SharedCard, { id: method2CardId, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: "2. Installation from Source Code - For Advanced Users",
                                    level: "h3",
                                    className: createSubtitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: [_jsx("p", { className: "mb-4", children: "This method requires Python and Git." }), _jsxs("ol", { className: "list-decimal list-outside pl-5 mb-4 space-y-3", children: [_jsx("li", { children: "Ensure Python (3.9+) and Git are installed." }), _jsxs("li", { children: [" ", "Clone the repository: ", _jsx("br", {}), " ", _jsx("code", { className: `${codeStyles} inline-block whitespace-pre-wrap my-2`, children: "git clone https://github.com/kz-lemon4ik/osu-lost-scores.git" }), " ", _jsx(SharedImageDisplay, { src: pageImages[3], alt: "Git clone example", onClick: () => openGallery(3), placeholderText: "[SCREENSHOT: Git clone command or downloading ZIP.]", className: createImageWrapperClasses(), enableHoverEffect: false }), " ", "Or download and extract ZIP.", " "] }), _jsxs("li", { children: [" ", "Navigate to the folder:", " ", _jsx("code", { className: `${codeStyles} inline-block whitespace-pre-wrap my-2`, children: "cd osu-lost-scores" }), " "] }), _jsxs("li", { children: [" ", "Create and activate a virtual environment (recommended): ", _jsx("br", {}), " ", _jsx("code", { className: `${codeStyles} inline-block whitespace-pre-wrap my-2`, children: "python -m venv .venv" }), " ", _jsx("br", {}), " Activate: (Windows cmd:", " ", _jsx("code", { className: codeStyles, children: ".venv\\Scripts\\activate.bat" }), ", PowerShell:", " ", _jsx("code", { className: codeStyles, children: ".venv\\Scripts\\Activate.ps1" }), ", Linux/macOS:", " ", _jsx("code", { className: codeStyles, children: "source .venv/bin/activate" }), ")", " "] }), _jsxs("li", { children: [" ", "Install dependencies: ", _jsx("br", {}), " ", _jsx("code", { className: `${codeStyles} inline-block whitespace-pre-wrap my-2`, children: "pip install -r requirements.txt" }), " ", _jsx(SharedImageDisplay, { src: pageImages[4], alt: "Pip install dependencies", onClick: () => openGallery(4), placeholderText: "[SCREENSHOT: Terminal showing pip install.]", className: createImageWrapperClasses(), enableHoverEffect: false }), " "] }), _jsxs("li", { children: [" ", "Run the application: ", _jsx("br", {}), " ", _jsx("code", { className: `${codeStyles} inline-block whitespace-pre-wrap my-2`, children: "python src/main.py" }), " ", _jsx(SharedImageDisplay, { src: pageImages[5], alt: "Running from source", onClick: () => openGallery(5), placeholderText: "[SCREENSHOT: Terminal showing python src/main.py.]", className: createImageWrapperClasses(), enableHoverEffect: false }), " "] })] })] }), _jsxs(SharedCard, { id: tocItems[4].id, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: tocItems[4].title.substring(tocItems[4].title.indexOf(" ") + 1),
                                    level: "h2",
                                    className: createTitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: [_jsxs("p", { className: "mb-4", children: [" ", "When you first run ", _jsx(HighlightText, { children: "osu! Lost Scores Analyzer" }), ", you will need to perform a few simple setup steps:", " "] }), _jsx(SharedImageDisplay, { src: pageImages[6], alt: "Main application window", onClick: () => openGallery(6), placeholderText: "[SCREENSHOT: Main application window (initial state).]", className: createImageWrapperClasses(), enableHoverEffect: false }), _jsxs("ul", { className: "list-disc list-outside pl-5 mb-4 space-y-3", children: [_jsxs("li", { children: [" ", _jsx("strong", { children: "Specifying the path to the osu! folder:" }), " The application will try to auto-detect the path. If it fails, manually specify the path to your root osu! game folder (containing ", _jsx("code", { className: codeStyles, children: "osu!.exe" }), ").", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "Your osu! nickname or User ID:" }), " Enter your exact osu! nickname or User ID.", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "osu! API Key (v1):" }), " Required to retrieve online data.", _jsxs("ul", { className: "list-circle list-outside pl-5 mt-2 space-y-2", children: [_jsxs("li", { children: ["Obtain from:", " ", _jsx("a", { href: "https://osu.ppy.sh/home/account/edit#oauth", target: "_blank", rel: "noopener noreferrer", className: clsx(accentLinkStyles, "break-all"), children: "https://osu.ppy.sh/home/account/edit#oauth" }), " ", "(login required).", " ", _jsx(SharedImageDisplay, { src: pageImages[7], alt: "osu! API page", onClick: () => openGallery(7), placeholderText: "[SCREENSHOT: osu! API page for key.]", className: createImageWrapperClasses(), enableHoverEffect: false }), " "] }), _jsx("li", { children: "Fill out the form (purpose: \"personal use for score analysis\")." }), _jsxs("li", { children: ["Copy the key and paste it into the application settings.", " ", _jsx(SharedImageDisplay, { src: pageImages[8], alt: "Application API key setup", onClick: () => openGallery(8), placeholderText: "[SCREENSHOT: Application API key setup window.]", className: createImageWrapperClasses(), enableHoverEffect: false }), " "] })] }), _jsx("div", { className: clsx("p-4 my-4 rounded-r-md", "bg-slate-800/60 border-l-4 border-lemon-400", "theme-is-light:bg-themeLight-primaryLightBg theme-is-light:border-l-4 theme-is-light:border-themeLight-primary"), children: _jsxs("p", { className: clsx("text-lavender-100", "theme-is-light:text-themeLight-text"), children: [" ", _jsx("strong", { children: "Important:" }), " Do not share your API key!", " "] }) })] })] }), _jsxs("p", { className: "mb-4", children: [" ", "These settings are usually made in a configuration window. After saving, the application is ready.", " "] })] }), _jsx(SharedCard, { id: tocItems[5].id, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: tocItems[5].title.substring(tocItems[5].title.indexOf(" ") + 1),
                                    level: "h2",
                                    className: createTitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: _jsxs("ul", { className: "list-disc list-outside pl-5 mb-4 space-y-3", children: [_jsxs("li", { children: [" ", _jsx("strong", { children: "For the .exe version:" }), " ", _jsxs("ol", { className: "list-decimal list-outside pl-5 mt-2 space-y-2", children: [" ", _jsx("li", { children: "Download the new launcher .exe from GitHub Releases." }), " ", _jsx("li", { children: "Replace the old launcher file." }), " ", _jsx("li", { children: "The new launcher may update components if needed." }), " "] }), " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "For the source code version:" }), " ", _jsxs("ol", { className: "list-decimal list-outside pl-5 mt-2 space-y-2", children: [" ", _jsx("li", { children: "Open a terminal in the project folder." }), " ", _jsxs("li", { children: ["If using Git: ", _jsx("code", { className: codeStyles, children: "git pull" })] }), " ", _jsxs("li", { children: ["Update dependencies:", " ", _jsx("code", { className: codeStyles, children: "pip install -r requirements.txt --upgrade" })] }), " ", _jsx("li", { children: "If using ZIP, download the new archive and repeat source installation." }), " "] }), " "] })] }) }), _jsxs(SharedCard, { id: tocItems[6].id, motion: { enableEntry: !isMotionDisabled }, title: {
                                    content: tocItems[6].title.substring(tocItems[6].title.indexOf(" ") + 1),
                                    level: "h2",
                                    className: createTitleClasses()
                                }, textStyles: { base: textBaseStyles, alignment: "justify" }, children: [_jsxs("ul", { className: "list-disc list-outside pl-5 mb-4 space-y-3", children: [_jsxs("li", { children: [" ", _jsx("strong", { children: "Antivirus blocks:" }), " Add application files to antivirus exclusions (false positive).", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "Launcher cannot download dependencies:" }), " Check internet connection and firewall/antivirus.", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "API key problems:" }), " Ensure correct key and its activity.", " "] }), _jsxs("li", { children: [" ", _jsx("strong", { children: "Cannot find osu! folder:" }), " Verify path correctness (must contain", " ", _jsx("code", { className: codeStyles, children: "osu!.exe" }), ").", " "] })] }), _jsx("p", { className: "mb-4", children: " If problems persist: " }), _jsxs("ul", { className: "list-disc list-outside pl-5 mb-4 space-y-3", children: [_jsxs("li", { children: [" ", "Check GitHub Issues:", " ", _jsx("a", { href: "https://github.com/kz-lemon4ik/osu-lost-scores/issues", target: "_blank", rel: "noopener noreferrer", className: `${accentLinkStyles} break-all`, children: "https://github.com/kz-lemon4ik/osu-lost-scores/issues" }), " "] }), _jsx("li", { children: " Create a new Issue with details if not found. " })] })] })] })] }), _jsx(ImageGalleryModal, { isOpen: isGalleryOpen, images: pageImages.filter((img) => !!img), currentIndex: currentImageIndex, onClose: closeGallery, onNext: nextImage, onPrev: prevImage })] }));
}
